# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        POS Loket Pelangi
    description:  POS Loket Pelangi
    keywords:     pos, loket pelangi
    language:     id
    robots:       index, follow

  stylesheets:    
                  - main.css
                  - bootstrap.css
                  - bootstrap-responsive.css

  javascripts:    
                  - html5.js
                  - js/jquery/jquery.js
                  - bootstrap-transition.js
                  - bootstrap-alert.js
                  - bootstrap-modal.js
                  - bootstrap-dropdown.js
                  - bootstrap-scrollspy.js
                  - bootstrap-tab.js
                  - bootstrap-tooltip.js
                  - bootstrap-popover.js
                  - bootstrap-button.js
                  - bootstrap-collapse.js
                  - bootstrap-carousel.js
                  - bootstrap-typeahead.js

  has_layout:     true
  layout:         layout
