Kelompok:
  connection: doctrine
  tableName: kelompok
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nama:
      type: string(120)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    keterangan:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    KelompokPelanggan:
      local: id
      foreign: kelompok_id
      type: many
KelompokPelanggan:
  connection: doctrine
  tableName: kelompok_pelanggan
  columns:
    kode_pelanggan:
      type: string(11)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    kelompok_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    Pelanggan:
      local: kode_pelanggan
      foreign: kode_pelanggan
      type: one
    Kelompok:
      local: kelompok_id
      foreign: id
      type: one
Lokasi:
  connection: doctrine
  tableName: lokasi
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nama:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    root_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    lft:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    rgt:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    level:
      type: integer(2)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Pelanggan:
      local: id
      foreign: lokasi_id
      type: many
BidangUsaha:
  connection: doctrine
  tableName: bidang_usaha
  columns:
    kode_usaha:
      type: string(6)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    keterangan:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    detail:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      default: F
      notnull: true
      autoincrement: false
    transfer:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      default: N
      notnull: true
      autoincrement: false
  relations:
    Pelanggan:
      local: kode_usaha
      foreign: kode_usaha
      type: many
Pelanggan:
  connection: doctrine
  tableName: pelanggan
  columns:
    kode_pelanggan:
      type: string(11)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    kode_salesman:
      type: string(9)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_loket:
      type: string(3)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_usaha:
      type: string(6)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_pos:
      type: string(5)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    lokasi_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nama:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nama_singkat:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    alamat:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    alamat_tagih:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    dtgl_masuk:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    attn:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    telepon:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    npwp:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    term:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    status:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      default: A
      notnull: true
      autoincrement: false
    takakura_pinjaman:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    takakura_uang_jaminan:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    tong_sampah_pinjaman:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    tong_sampah_uang_jaminan:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    telepon2:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    transfer:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      default: N
      notnull: true
      autoincrement: false
    cetak_harga:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      default: F
      notnull: true
      autoincrement: false
    pembayaran:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      default: K
      notnull: true
      autoincrement: false
  relations:
    Salesman:
      local: kode_salesman
      foreign: kode_salesman
      type: one
    Lokasi:
      local: lokasi_id
      foreign: id
      type: one
    Loket:
      local: kode_loket
      foreign: kode_loket
      type: one
    Wilayah:
      local: kode_pos
      foreign: kode_pos
      type: one
    BidangUsaha:
      local: kode_usaha
      foreign: kode_usaha
      type: one
    JenisBayar:
      local: pembayaran
      foreign: kode_jenis_bayar
      type: one
    StatusPelanggan:
      local: status
      foreign: kode_status_pelanggan
      type: one
    KelompokPelanggan:
      local: kode_pelanggan
      foreign: kode_pelanggan
      type: many
JenisBayar:
  connection: doctrine
  tableName: jenis_bayar
  columns:
    kode_jenis_bayar:
      type: string(1)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    keterangan:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Pelanggan:
      local: kode_jenis_bayar
      foreign: pembayaran
      type: many
Loket:
  connection: doctrine
  tableName: loket
  columns:
    kode_loket:
      type: string(3)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    keterangan:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    alamat:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    telepon:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    telepon2:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fax:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kontak:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inactive:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Pelanggan:
      local: kode_loket
      foreign: kode_loket
      type: many
    Salesman:
      local: kode_loket
      foreign: kode_loket
      type: many
Salesman:
  connection: doctrine
  tableName: salesman
  columns:
    kode_salesman:
      type: string(9)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    kode_loket:
      type: string(3)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nama:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    transfer:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      default: N
      notnull: true
      autoincrement: false
    alamat:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    status:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      default: A
      notnull: true
      autoincrement: false
  relations:
    Loket:
      local: kode_loket
      foreign: kode_loket
      type: one
    Pelanggan:
      local: kode_salesman
      foreign: kode_salesman
      type: many
StatusPelanggan:
  connection: doctrine
  tableName: status_pelanggan
  columns:
    kode_status_pelanggan:
      type: string(1)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    keterangan:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Pelanggan:
      local: kode_status_pelanggan
      foreign: status
      type: many
Wilayah:
  connection: doctrine
  tableName: wilayah
  columns:
    kode_pos:
      type: string(5)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    keterangan:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    latitude:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    longitude:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    transfer:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      default: N
      notnull: true
      autoincrement: false
  relations:
    Pelanggan:
      local: kode_pos
      foreign: kode_pos
      type: many
